---
# Markdown linting configuration for Super Linter

# Default state for all rules
default: true

# Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  tables: false

# Multiple top-level headings - Allow for README structure
MD025: false

# Trailing punctuation in heading - Disable
MD026: false

# Inline HTML - Allow for better formatting
MD033: false

# Bare URLs - Allow for simplicity
MD034: false

# Code block style - Require language specification
MD040: true

# Hard tabs - Disable (we use spaces)
MD010: false

# Trailing spaces - Should be avoided
MD009: true